from django.http import Http404, HttpResponse
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, "singlepage/index.html")


# The texts are much longer in reality, but have
# been shortened here to save space
texto1 = "Qui ea quis elit nisi reprehenderit laboris officia aliquip excepteur. Ut tempor magna enim in ipsum pariatur enim voluptate commodo. Excepteur reprehenderit non laborum nisi dolore incididunt cillum do enim quis fugiat.Enim in aliqua sint irure proident. Nisi veniam duis esse dolor nulla. Cillum elit ex excepteur cupidatat dolore aliqua pariatur magna dolore ipsum eiusmod excepteur labore. Excepteur eu quis sunt do esse consequat consectetur. Aliquip in quis adipisicing incididunt magna commodo minim minim ullamco aliqua. Incididunt consectetur tempor excepteur exercitation nisi cillum deserunt excepteur incididunt Lorem eiusmod Lorem anim aliquip. Adipisicing fugiat deserunt aliquip elit irure dolor id cillum aliqua elit magna mollit. Incididunt pariatur duis mollit exercitation aute irure mollit minim adipisicing consequat nisi id. Irure id quis velit est qui commodo consequat ipsum excepteur ad nostrud. Enim et nostrud eu laboris. Duis nulla ullamco et ut ad. Amet pariatur et excepteur consequat exercitation amet tempor ut velit ut commodo. Consectetur anim excepteur excepteur enim excepteur deserunt exercitation. Velit cillum cillum minim proident duis commodo mollit laboris nisi eu do ex irure voluptate. Magna elit ea reprehenderit commodo magna ut voluptate dolore proident. Laborum mollit do elit veniam. Proident consequat magna incididunt amet ex."
texto1 = texto1 + "Qui ea quis elit nisi reprehenderit laboris officia aliquip excepteur. Ut tempor magna enim in ipsum pariatur enim voluptate commodo. Excepteur reprehenderit non laborum nisi dolore incididunt cillum do enim quis fugiat.Enim in aliqua sint irure proident. Nisi veniam duis esse dolor nulla. Cillum elit ex excepteur cupidatat dolore aliqua pariatur magna dolore ipsum eiusmod excepteur labore. Excepteur eu quis sunt do esse consequat consectetur. Aliquip in quis adipisicing incididunt magna commodo minim minim ullamco aliqua. Incididunt consectetur tempor excepteur exercitation nisi cillum deserunt excepteur incididunt Lorem eiusmod Lorem anim aliquip. Adipisicing fugiat deserunt aliquip elit irure dolor id cillum aliqua elit magna mollit. Incididunt pariatur duis mollit exercitation aute irure mollit minim adipisicing consequat nisi id. Irure id quis velit est qui commodo consequat ipsum excepteur ad nostrud. Enim et nostrud eu laboris. Duis nulla ullamco et ut ad. Amet pariatur et excepteur consequat exercitation amet tempor ut velit ut commodo. Consectetur anim excepteur excepteur enim excepteur deserunt exercitation. Velit cillum cillum minim proident duis commodo mollit laboris nisi eu do ex irure voluptate. Magna elit ea reprehenderit commodo magna ut voluptate dolore proident. Laborum mollit do elit veniam. Proident consequat magna incididunt amet ex."
texto1 = texto1 + "Qui ea quis elit nisi reprehenderit laboris officia aliquip excepteur. Ut tempor magna enim in ipsum pariatur enim voluptate commodo. Excepteur reprehenderit non laborum nisi dolore incididunt cillum do enim quis fugiat.Enim in aliqua sint irure proident. Nisi veniam duis esse dolor nulla. Cillum elit ex excepteur cupidatat dolore aliqua pariatur magna dolore ipsum eiusmod excepteur labore. Excepteur eu quis sunt do esse consequat consectetur. Aliquip in quis adipisicing incididunt magna commodo minim minim ullamco aliqua. Incididunt consectetur tempor excepteur exercitation nisi cillum deserunt excepteur incididunt Lorem eiusmod Lorem anim aliquip. Adipisicing fugiat deserunt aliquip elit irure dolor id cillum aliqua elit magna mollit. Incididunt pariatur duis mollit exercitation aute irure mollit minim adipisicing consequat nisi id. Irure id quis velit est qui commodo consequat ipsum excepteur ad nostrud. Enim et nostrud eu laboris. Duis nulla ullamco et ut ad. Amet pariatur et excepteur consequat exercitation amet tempor ut velit ut commodo. Consectetur anim excepteur excepteur enim excepteur deserunt exercitation. Velit cillum cillum minim proident duis commodo mollit laboris nisi eu do ex irure voluptate. Magna elit ea reprehenderit commodo magna ut voluptate dolore proident. Laborum mollit do elit veniam. Proident consequat magna incididunt amet ex."
texto2 = "Occaecat aliqua duis proident in quis aliquip do consectetur anim nisi. Cillum sit sint Lorem magna esse cillum aliqua non velit ea veniam ipsum non. Sunt cupidatat veniam dolor sit do aute eu aliquip reprehenderit ut aliquip dolore sint ipsum. Commodo culpa pariatur in id mollit amet. Qui cupidatat est consectetur elit amet amet. Deserunt laborum cillum irure adipisicing."
texto3 = "Id ipsum proident pariatur culpa velit ex laborum nulla incididunt veniam. In aute mollit officia esse enim. Adipisicing ea consequat et amet consequat pariatur amet pariatur labore quis sint anim Lorem. Pariatur proident commodo irure sit dolore cupidatat tempor non labore occaecat ut."
texts = [texto1, texto2, texto3]


def section(request, num):
    if 1 <= num <= 3:
        return HttpResponse(texts[num - 1])
    else:
        raise Http404("No such section")
